#!/usr/bin/env python
# coding: utf-8

# In[2]:


from selenium.webdriver.chrome.options import Options
import pandas as pd
import requests as req
import re
from selenium import webdriver
from datetime import date
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException

DRIVER_PATH = 'C:/Users/berat/webdriver/chromedriver' #BILGISAYARDA chromedriver'ın bulunduğu yer
options = Options()
options.headless = True
options.add_argument("--window-size=1920,1200")
driver = webdriver.Chrome(options=options, executable_path=DRIVER_PATH)

#### IFRAME
top_bulten_xpath = "//*[@id='post-19576']/div/div/div/div/div/div[2]/div/div/div/div/div[1]/div/div/div[1]/div/div/div/div[5]/div[1]/div/a/div/img"
driver.get("https://infoyatirim.com/hisse-viop-bulteni/page/1/")
driver.find_element_by_xpath(top_bulten_xpath).click()
src = driver.find_element_by_css_selector("iframe").get_attribute("src")
driver.get(src)
try:
    WebDriverWait(driver, timeout=20).until(EC.visibility_of_all_elements_located((By.XPATH, "//table/tbody/tr/td/ul/li/b/span")))
except TimeoutException:
    print("Timed out waiting for page to load")
    driver.quit()
    
sirket_haberleri = driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr[3]/td/ul/li")
news_list1 = []
news_list1_codes = []
date_list = []
aracı_kurum = []
date = date.today()
for news in sirket_haberleri:
    try:
        if '&' in news.find_element_by_xpath('./b/span').text:
            for i in range(0,len(news.find_element_by_xpath('./b/span').text.split(' &'))):
                news_list1_codes.append(news.find_element_by_xpath('./b/span').text[:-2].split(' &')[i])
                news_list1.append(news.find_element_by_xpath('./span').text)
                date_list.append(date)
                aracı_kurum.append('İnfo Yatırım')
        else:
            news_list1.append(news.find_element_by_xpath('./span').text)
            news_list1_codes.append(news.find_element_by_xpath('./b/span').text[:-2])
            date_list.append(date)
            aracı_kurum.append('İnfo Yatırım')
    except:
        print('xd')
    finally:
        sub_news_list1 = news.find_elements_by_xpath('./ul/li')
        for snews in sub_news_list1:
            news_list1.append(snews.find_element_by_xpath('./span').text)
            news_list1_codes.append(news.find_element_by_xpath('./b/span').text[:-2])
            date_list.append(date)
            aracı_kurum.append('İnfo Yatırım')
            
#data1 - Sirket haberleri
data1 = pd.DataFrame(list(zip(date_list, news_list1_codes, news_list1)))
data1.index = news_list1_codes
data1.columns = ['date', 'code','sentiment']
data1 = data1[data1.sentiment != '']

codes = data1['code'].tolist()
news = data1['sentiment'].tolist()

codes1 = []
news1 = []
for i in range(0, len(codes)):
    if '&' in codes[i]:
        for code in codes[i].split('&'):
            codes1.append(code.strip())
            news1.append(news[i])
    else:
        codes1.append(codes[i].strip())
        news1.append(news[i])
        
#data1 - Sirket haberleri
data1 = pd.DataFrame(list(zip(aracı_kurum, date_list, codes1, news1)))
data1.columns = ['aracı_kurum','date', 'code','sentiment']

data1


# In[13]:


def info_yatırım():
    from selenium.webdriver.chrome.options import Options
    import pandas as pd
    import requests as req
    import re
    from selenium import webdriver
    from datetime import date
    from selenium.webdriver.common.by import By
    from selenium.webdriver.support.ui import WebDriverWait
    from selenium.webdriver.support import expected_conditions as EC
    from selenium.common.exceptions import TimeoutException

    DRIVER_PATH = 'C:/Users/berat/webdriver/chromedriver' #BILGISAYARDA chromedriver'ın bulunduğu yer
    options = Options()
    options.headless = True
    options.add_argument("--window-size=1920,1200")
    driver = webdriver.Chrome(options=options, executable_path=DRIVER_PATH)

    #### IFRAME
    top_bulten_xpath = "//*[@id='post-19576']/div/div/div/div/div/div[2]/div/div/div/div/div[1]/div/div/div[1]/div/div/div/div[5]/div[1]/div/a/div/img"
    driver.get("https://infoyatirim.com/hisse-viop-bulteni/page/1/")
    driver.find_element_by_xpath(top_bulten_xpath).click()
    src = driver.find_element_by_css_selector("iframe").get_attribute("src")
    driver.get(src)
    try:
        WebDriverWait(driver, timeout=20).until(EC.visibility_of_all_elements_located((By.XPATH, "//table/tbody/tr/td/ul/li/b/span")))
    except TimeoutException:
        print("Timed out waiting for page to load")
        driver.quit()

    sirket_haberleri = driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr[3]/td/ul/li")
    news_list1 = []
    news_list1_codes = []
    date_list = []
    aracı_kurum = []
    date = date.today()
    for news in sirket_haberleri:
        try:
            if '&' in news.find_element_by_xpath('./b/span').text:
                for i in range(0,len(news.find_element_by_xpath('./b/span').text.split(' &'))):
                    news_list1_codes.append(news.find_element_by_xpath('./b/span').text[:-2].split(' &')[i])
                    news_list1.append(news.find_element_by_xpath('./span').text)
                    date_list.append(date)
                    aracı_kurum.append('İnfo Yatırım')
            else:
                news_list1.append(news.find_element_by_xpath('./span').text)
                news_list1_codes.append(news.find_element_by_xpath('./b/span').text[:-2])
                date_list.append(date)
                aracı_kurum.append('İnfo Yatırım')
        except:
            print('xd')
        finally:
            sub_news_list1 = news.find_elements_by_xpath('./ul/li')
            for snews in sub_news_list1:
                news_list1.append(snews.find_element_by_xpath('./span').text)
                news_list1_codes.append(news.find_element_by_xpath('./b/span').text[:-2])
                date_list.append(date)
                aracı_kurum.append('İnfo Yatırım')

    #data1 - Sirket haberleri
    data1 = pd.DataFrame(list(zip(date_list, news_list1_codes, news_list1)))
    data1.index = news_list1_codes
    data1.columns = ['date', 'code','sentiment']
    data1 = data1[data1.sentiment != '']

    codes = data1['code'].tolist()
    news = data1['sentiment'].tolist()

    codes1 = []
    news1 = []
    for i in range(0, len(codes)):
        if '&' in codes[i]:
            for code in codes[i].split('&'):
                codes1.append(code.strip())
                news1.append(news[i])
        else:
            codes1.append(codes[i].strip())
            news1.append(news[i])

    #data1 - Sirket haberleri
    data1 = pd.DataFrame(list(zip(aracı_kurum, date_list, codes1, news1)))
    data1.columns = ['aracı_kurum','date', 'code','sentiment']

    return data1

slack_token = 'xoxb-1310569939731-1313227713634-fKQuc3HqgyqeWm0o1Iq7itoT'
slack_channel = '#messagebot'
slack_icon_url = 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuGqps7ZafuzUsViFGIremEL2a3NR0KO0s0RTCMXmzmREJd5m4MA&s'
slack_user_name = 'datawriter'
import requests
import json
def post_message_to_slack(text, blocks = None):
    return requests.post('https://slack.com/api/chat.postMessage', {
        'token': slack_token,
        'channel': slack_channel,
        'text': text,
        'icon_url': slack_icon_url,
        'username': slack_user_name,
        'blocks': json.dumps(blocks) if blocks else None
    }).json()	

data = info_yatırım()

def telegram_bot_sendtext(bot_message):
    bot_token = '1342173314:AAFuLuqcKXc0L7T7w0L2gnRXd7ISaQnnfOc'
    bot_chatID = '-458771490'
    send_text = 'https://api.telegram.org/bot' + bot_token + '/sendMessage?chat_id=' + bot_chatID + '&parse_mode=Markdown&text=' + bot_message
    response = requests.get(send_text)
    return response.json()
    

news_text = []
for i in range(0,len(data)):
    text_to_telegram = data.iloc[i,0] + '\n' + str(data.iloc[i,1]) + '\n' + data.iloc[i,2] + '\n' + data.iloc[i,3] + '\n' + '__________________________________'
    telegram_bot_sendtext(text_to_telegram)

